@echo off
setlocal EnableDelayedExpansion

set BASIC_SOURCE=basic\source.bas
if not "%~1"=="" set BASIC_SOURCE=%~1

if not exist target mkdir target

del target\*.d81 2>nul
del target\*.lst 2>nul
del target\*.lbl 2>nul
del target\basic65c 2>nul
del target\runtime.prg 2>nul
del target\*.prg 2>nul

rem The runtime must assemble BEFORE the compiler: the template generator
rem bakes runtime addresses from target\runtime.lbl into
rem src\gen\bin-templates.inc, which the compiler includes. Assembling the
rem compiler first would embed stale addresses whenever the runtime moves
rem (the harness byte-diff catches exactly that drift).
rem No -a here: the harness links this same source without it, and the
rem shipped RUNTIME.PRG image must assemble byte-identically both ways
rem (runtime text comparisons handle ASCII and PETSCII input explicitly).
.\64tass.exe --cbm-prg src\runtime\runtime.asm -l target\runtime.lbl -L target\runtime.lst -o target\runtime.prg
if errorlevel 1 exit /b 1

rem Derive binary code templates from the compiler's text templates for the
rem native backend (see docs\native-backend.md). Requires Python; skipped
rem with a warning if unavailable (the committed include is then used as-is).
where python >nul 2>nul
if %ERRORLEVEL%==0 (
    python tools\gen-bin-templates.py
    if errorlevel 1 exit /b 1
) else (
    echo Warning: python not found; skipping bin-template generation
)

.\64tass.exe --cbm-prg -a src\basic65c.asm -l target\basic65c.lbl -L target\basic65c.lst -o target\basic65c
if errorlevel 1 exit /b 1

rem banked graphics blob: assembled at $8000, read into bank 5 by rtinit
rem when a compiled program uses graphics (gfxshared.inc is generated by
rem gen-bin-templates.py above from runtime.lbl)
.\64tass.exe --cbm-prg src\gfx\gfx.asm -o target\gfx.prg
if errorlevel 1 exit /b 1

rem harness bootstraps must survive the target\*.prg wipe above
.\petcat.exe -w65 -l 2001 -o target\bootstrap.prg -- tools\bootstrap.bas
if errorlevel 1 exit /b 1
if errorlevel 1 exit /b 1

rem Builds every BASIC fixture, including graphics demos named basic\gfx*.bas.
for %%F in (basic\*.bas) do (
    .\petcat.exe -w65 -l 2001 -o "target\%%~nF.prg" -- "%%F"
    if errorlevel 1 exit /b 1
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\fix-basic65-petcat-tokens.ps1 "target\%%~nF.prg"
    if errorlevel 1 exit /b 1
)

if /I not "%BASIC_SOURCE%"=="basic\source.bas" (
    .\petcat.exe -w65 -l 2001 -o target\source.prg -- "%BASIC_SOURCE%"
    if errorlevel 1 exit /b 1
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\fix-basic65-petcat-tokens.ps1 target\source.prg
    if errorlevel 1 exit /b 1
)

set HAVE_OUT_PRG=0
if exist target\out.asm.seq (
    powershell -NoProfile -ExecutionPolicy Bypass -Command "$out=(Get-Item -LiteralPath 'target\out.asm.seq').LastWriteTime; $deps=@($env:BASIC_SOURCE,'src\basic65c.asm','src\runtime\runtime.asm') + (Get-ChildItem -LiteralPath 'basic' -Filter '*.bas').FullName; foreach($dep in $deps){ if($out -lt (Get-Item -LiteralPath $dep).LastWriteTime){ exit 2 } }"
    if errorlevel 2 (
        echo Warning: target\out.asm.seq is stale; continuing without OUT.PRG
    ) else (
        .\64tass.exe --cbm-prg --m45gs02 src\runtime\runtime.asm target\out.asm.seq -o target\out.prg
        if errorlevel 1 (
            echo Warning: target\out.asm.seq did not assemble; continuing without OUT.PRG
            del target\out.prg 2>nul
        ) else (
            set HAVE_OUT_PRG=1
        )
    )
)

cd target
..\c1541.exe -format "basic65c,01" d81 basic65c.d81
if errorlevel 1 exit /b 1
..\c1541.exe -attach basic65c.d81 -write basic65c basic65c
if errorlevel 1 exit /b 1
..\c1541.exe -attach basic65c.d81 -write basic65t.prg "+b65tpl"
if errorlevel 1 exit /b 1
..\c1541.exe -attach basic65c.d81 -write gfx.prg "+b65gfx"
if errorlevel 1 exit /b 1
..\c1541.exe -attach basic65c.d81 -write runtime.prg "+b65rtm"
if errorlevel 1 exit /b 1
for %%F in (*.prg) do (
    if /I not "%%F"=="out.prg" if /I not "%%F"=="runtime.prg" if /I not "%%F"=="gfx.prg" if /I not "%%F"=="basic65t.prg" (
        set "DISKNAME=%%F"
        if /I "!DISKNAME:~0,3!"=="gfx" if not "!DISKNAME:~16!"=="" set "DISKNAME=%%~nF"
        if not "!DISKNAME:~16!"=="" set "DISKNAME=!DISKNAME:~0,16!"
        ..\c1541.exe -attach basic65c.d81 -write "%%F" "!DISKNAME!"
        if errorlevel 1 exit /b 1
    )
)
rem out.prg is no longer pre-loaded onto the D81: the compiler writes its
rem own native OUT.PRG there during compilation
cd ..

echo Built target\basic65c.d81
echo Built BASIC test PRGs from basic\*.bas, including basic\gfx*.bas
if /I not "%BASIC_SOURCE%"=="basic\source.bas" echo Built SOURCE.PRG from %BASIC_SOURCE%
if "%HAVE_OUT_PRG%"=="1" echo Built target\out.prg and added it to the D81
